### ISSUE TITLE
storybook本地启动报错

### ISSUE THREAD

**Issue by lijianru** [lijianru/react-template-use-vite#26]
```
$ start-storybook -p 6006
info @storybook/react v6.2.9
info 
info => Loading presets
info => Loading 1 config file in "/Users/lijianru/demo/react-template-use-vite/.storybook"
info => Loading 7 other files in "/Users/lijianru/demo/react-template-use-vite/.storybook"
info => Adding stories defined in "/Users/lijianru/demo/react-template-use-vite/.storybook/main.js"
info => Using prebuilt manager
info => Using implicit CSS loaders
info => Using custom postcss.config.js
info => Using default Webpack4 setup
(node:39866) DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 1/5 modules 4 active ...e-vite/node_modules/babel-loader/lib/index.js??ref--4-0!/Users/lijianru/demo/react-template-use-vite/.storybook/generated-stories-entry.jsBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
11% building 9/21 modules 12 active /Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.jsinfo => Using cached manager
webpack built preview 556022686543feadf178 in 7111ms
✖ ｢wdm｣: Hash: 556022686543feadf178
Version: webpack 4.46.0
Time: 7111ms
Built at: 2021/10/20 下午6:56:02
                            Asset      Size        Chunks                          Chunk Names
               0.iframe.bundle.js   202 KiB             0  [emitted]               
           0.iframe.bundle.js.map   143 KiB             0  [emitted] [dev]         
               1.iframe.bundle.js   212 KiB             1  [emitted]               
           1.iframe.bundle.js.map   205 KiB             1  [emitted] [dev]         
               2.iframe.bundle.js  87.3 KiB             2  [emitted]               
           2.iframe.bundle.js.map    82 KiB             2  [emitted] [dev]         
               3.iframe.bundle.js   372 KiB             3  [emitted]        [big]  
           3.iframe.bundle.js.map   412 KiB             3  [emitted] [dev]         
               4.iframe.bundle.js  14.9 KiB             4  [emitted]               
           4.iframe.bundle.js.map  16.5 KiB             4  [emitted] [dev]         
                      iframe.html  4.34 KiB                [emitted]               
            main.iframe.bundle.js  52.1 KiB          main  [emitted]               main
        main.iframe.bundle.js.map  19.1 KiB          main  [emitted] [dev]         main
    runtime~main.iframe.bundle.js  36.3 KiB  runtime~main  [emitted]               runtime~main
runtime~main.iframe.bundle.js.map  37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
    vendors~main.iframe.bundle.js  4.68 MiB  vendors~main  [emitted]        [big]  vendors~main
vendors~main.iframe.bundle.js.map  4.34 MiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/core-server/dist/cjs/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 172 bytes {main} [built]
[./.storybook/generated-stories-entry.js] 292 bytes {main} [built]
[./.storybook/preview.js] 175 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 3.65 KiB {main} [built]
[./.storybook/storybook-init-framework-entry.js] 26 bytes {main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js] 2.57 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.57 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.58 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js] 2.58 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js] 2.57 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js] 2.57 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.57 KiB {vendors~main} [built]
[./node_modules/@storybook/core-server/dist/cjs/globals/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 7.68 KiB {vendors~main} [built]
    + 1180 hidden modules

ERROR in ./src/components/Header/header.css (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js??ref--11-2!./src/components/Header/header.css)
Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
 @ ./src/components/Header/header.css 2:26-208 53:4-74:5 56:18-200
 @ ./src/components/Header/index.tsx
 @ ./src/components/Header/Header.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/core-server/dist/cjs/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./src/components/Button/button.css (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js??ref--11-2!./src/components/Button/button.css)
Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
 @ ./src/components/Button/button.css 2:26-208 53:4-74:5 56:18-200
 @ ./src/components/Button/index.tsx
 @ ./src/components/Button/Button.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/core-server/dist/cjs/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.24 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.99 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
    at /Users/lijianru/demo/react-template-use-vite/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:104:7)
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
    at /Users/lijianru/demo/react-template-use-vite/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/lijianru/demo/react-template-use-vite/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/lijianru/demo/react-template-use-vite/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:104:7)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by lijianru** [comment]
fixed! 2bade3cf34e6bd7e8c782edf7e5ef29e594bbec3
